#ANDREW ADDED
gems:
  - jekyll-postfiles
  - jekyll-sitemap
  
plugins:
  - jekyll-sitemap
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  
include: ["_posts"]
  
#ANDREW ADDED

# general configuration
url: http://andburch.github.io
baseurl: ''

sass:
    sass_dir: ./assets

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/pawpaw.png"
  # author will appear under the avatar (optional)
  author: "Andrew Burchill"
  # tagline will appear under the title (optional)
  tagline: "Myrmecologist, collective behaviorist, and wanna-be engineer.  #undisciplined "
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Exclude non-site files:
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "anne_pro_macros.xlsx", "notes.txt"]

# Dependencies
markdown: kramdown
kramdown:
  syntax-highlighter:  rouge
highlighter: rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Hyde stuff
#baseurl: "/" # If you are making a gh-pages project blog, this is
                        # the name of your project repo, preceded by a /'
                        # Set it to just "/" if you are making a user page.
                        
baseurlknitr:  "/" # This will always be your baseurl plus an extra '/'
                                # at the end.  It's used only when knitr renders
                                # your R Markdown files.
                                
# Site-wide links
links:
  about_me:           /about/
  blog:            /blog/
  cv:            /cv.pdf
  pubs_google:            https://scholar.google.com/citations?user=zbe4q7YAAAAJ
  pubs_orcid:            https://orcid.org/0000-0002-4197-6689
  pubs_researchgate:            https://www.researchgate.net/profile/Andrew_Burchill
  home: "/"

# Other stuff
facepic: /images/andrewmacho.jpg
                                

# set limit on number of post to appear on Home page
homepostlimit: 4
# The thing that gets excerpts
excerpt_separator: <!--more-->  # you can specify your own separator, of course.

# Disqus comments:
disqus:           false
shortname:        zachburchill # TO-DO: get a disqus account and change this

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post

author:
  name:           'Andrew Burchill'
  url:            https://andburch.github.io

github:
  repo:           https://github.com/andburch
  

